# Generated by Django 5.2.8 on 2025-12-13 21:33

import accounts.models
import accounts.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth0_id', models.CharField(help_text='The user_id returned by Auth0 (e.g. auth0|abcd1234)', max_length=200, unique=True)),
                ('email', models.EmailField(help_text='Email stored locally for quick lookup & linking to profiles.', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=20)),
                ('invited_at', models.DateTimeField(blank=True, help_text='When this user was invited (null if created outside the flow)', null=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active')], default='active', help_text='User status: invited (password not set yet) or active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text='The super_admin who invited this user (null if created outside the flow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='accounts.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text='Duplicate email for UI convenience.', max_length=254)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(blank=True, default='', help_text='Preferred language(s)', max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.mentee_profile_picture_upload_path, validators=[accounts.validators.FileSizeValidator(5), accounts.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('interests', models.JSONField(blank=True, default=list, help_text="List of selected interests (e.g., ['Web Development', 'AI/ML', 'Data Science'])")),
                ('user_type', models.CharField(blank=True, choices=[('student', 'Student'), ('professional', 'Professional'), ('entrepreneur', 'Entrepreneur'), ('career_changer', 'Career Changer'), ('job_seeker', 'Job Seeker')], help_text='Type of user (Student, Professional, Entrepreneur, Career Changer, Job Seeker)', max_length=50, null=True)),
                ('session_frequency', models.CharField(blank=True, choices=[('once_week', 'Once a week'), ('every_two_weeks', 'Every two weeks'), ('once_month', 'Once a month'), ('flexible', 'Flexible')], help_text='Preferred session frequency', max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned')], default='active', help_text='Mentee account status for access control.', max_length=20)),
                ('banned_at', models.DateTimeField(blank=True, help_text='When the mentee was banned (if applicable).', null=True)),
                ('ban_reason', models.TextField(blank=True, help_text='Reason provided when banning the mentee (optional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(blank=True, help_text='Admin/Super Admin who performed the ban.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_mentees', to='accounts.appuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to='accounts.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Mentor email (duplicate for UI convenience).', max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('professional_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField()),
                ('bio', models.TextField()),
                ('languages', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.mentor_profile_picture_upload_path, validators=[accounts.validators.FileSizeValidator(5), accounts.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('cv', models.FileField(upload_to=accounts.models.mentor_cv_upload_path, validators=[accounts.validators.FileSizeValidator(10), accounts.validators.FileExtensionValidator(['pdf'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('banned', 'Banned')], default='pending', max_length=20)),
                ('banned_at', models.DateTimeField(blank=True, help_text='When the mentor was banned (if applicable).', null=True)),
                ('ban_reason', models.TextField(blank=True, help_text='Reason provided when banning the mentor (optional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(blank=True, help_text='Admin/Super Admin who performed the ban.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_mentors', to='accounts.appuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='accounts.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLinkingVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_auth0_id', models.CharField(help_text='The Auth0 ID of the new social account (e.g., google-oauth2|123)', max_length=200)),
                ('new_email', models.EmailField(help_text='Email of the new social account (should match existing_user.email)', max_length=254)),
                ('token', models.CharField(help_text='Cryptographically secure token for verification', max_length=64, unique=True)),
                ('verified', models.BooleanField(default=False, help_text='Whether this verification has been completed')),
                ('expired', models.BooleanField(default=False, help_text='Whether this verification has expired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this verification token expires (default: 15 minutes)')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the verification was completed', null=True)),
                ('registration_data', models.JSONField(help_text='Stores profile data (full_name, field_of_study, etc.) until verification')),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], help_text='Role chosen during registration', max_length=20)),
                ('existing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linking_verifications', to='accounts.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_ac_token_188a6f_idx'), models.Index(fields=['expires_at'], name='accounts_ac_expires_02d21a_idx')],
            },
        ),
    ]
