# Generated by Django 5.2.8 on 2025-12-14 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address for password reset', max_length=254)),
                ('auth0_user_id', models.CharField(help_text='Auth0 user ID for updating password', max_length=200)),
                ('token', models.CharField(help_text='Cryptographically secure reset token', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this token expires (default: 1 hour)')),
                ('used', models.BooleanField(default=False, help_text='Whether this token has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_pa_token_affdf2_idx'), models.Index(fields=['expires_at'], name='accounts_pa_expires_01b447_idx'), models.Index(fields=['email'], name='accounts_pa_email_6f6f26_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Cryptographically secure verification token', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this token expires (default: 24 hours)')),
                ('verified', models.BooleanField(default=False, help_text='Whether the email has been verified with this token')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the email was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to='accounts.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_em_token_5f2b37_idx'), models.Index(fields=['expires_at'], name='accounts_em_expires_f36bd3_idx')],
            },
        ),
    ]
