# Generated by Django 5.2.8 on 2025-12-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank Name for Payouts', max_length=255),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='iban',
            field=models.CharField(blank=True, help_text='International Bank Account Number (IBAN)', max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='swift_bic',
            field=models.CharField(blank=True, help_text='Bank Identifier Code (SWIFT/BIC)', max_length=50),
        ),
    ]
