# Generated by Django 5.2.8 on 2025-12-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text="List of skills (e.g., ['Python', 'Django', 'Machine Learning'])"),
        ),
    ]
