# Generated by Django 5.2.8 on 2025-12-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mentorprofile_bank_name_mentorprofile_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance available for payout', max_digits=10),
        ),
    ]
