# Generated by Django 5.2.8 on 2025-12-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mentorprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='social_picture_url',
            field=models.URLField(blank=True, help_text='Profile picture URL from social auth (Google/LinkedIn)', max_length=500, null=True),
        ),
    ]
