# Generated by Django 5.2.8 on 2025-12-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_social_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='current_role',
            field=models.CharField(blank=True, help_text="Current job/role (e.g., 'Marketing Specialist', 'Software Engineer')", max_length=255, null=True),
        ),
    ]
