# Generated by Django 5.2.8 on 2025-12-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_current_role_to_mentee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeprofile',
            name='interests',
        ),
    ]
