# Generated by Django 5.2.8 on 2025-12-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_interests_from_mentee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="List of preferred languages (e.g., ['English', 'French', 'Arabic'])"),
        ),
    ]
