# Generated by Django 5.2.8 on 2025-12-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_change_language_to_languages_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text="List of skills (e.g., ['JavaScript', 'React', 'Python'])"),
        ),
    ]
