# Generated by Django 5.2.8 on 2025-12-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_skills_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='social_picture_url',
            field=models.URLField(blank=True, help_text='Profile picture URL from social auth (Google/LinkedIn)', max_length=500, null=True),
        ),
    ]
