# Generated by Django 5.2.8 on 2025-12-19 16:33

from django.db import migrations, models


def convert_languages_to_json_format(apps, schema_editor):
    """
    Convert existing string languages to JSON array format using raw SQL.
    This must happen BEFORE the AlterField because PostgreSQL can't convert
    arbitrary strings to JSON automatically.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # First, update all non-null, non-empty string values to JSON array format
        # "English" -> '["English"]'
        # "English, French" -> '["English", "French"]'
        cursor.execute("""
            UPDATE accounts_mentorprofile 
            SET languages = (
                SELECT jsonb_agg(trim(elem))
                FROM unnest(string_to_array(languages::text, ',')) AS elem
                WHERE trim(elem) != ''
            )::text
            WHERE languages IS NOT NULL 
            AND languages != ''
            AND languages NOT LIKE '[%'
        """)
        
        # Set empty strings and NULLs to empty JSON array
        cursor.execute("""
            UPDATE accounts_mentorprofile 
            SET languages = '[]'
            WHERE languages IS NULL OR languages = ''
        """)


def revert_languages_to_string(apps, schema_editor):
    """Revert JSON arrays back to comma-separated strings."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE accounts_mentorprofile 
            SET languages = (
                SELECT string_agg(elem::text, ', ')
                FROM jsonb_array_elements_text(languages::jsonb) AS elem
            )
            WHERE languages IS NOT NULL AND languages != '[]'
        """)
        
        cursor.execute("""
            UPDATE accounts_mentorprofile 
            SET languages = ''
            WHERE languages = '[]' OR languages IS NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_mentorprofile_social_picture_url'),
    ]

    operations = [
        # First convert existing string data to JSON format
        migrations.RunPython(
            convert_languages_to_json_format,
            reverse_code=revert_languages_to_string,
        ),
        # Then alter the field type to JSONField
        migrations.AlterField(
            model_name='mentorprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="List of languages (e.g., ['English', 'French'])"),
        ),
    ]
