# Generated by Django 5.2.8 on 2025-12-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_convert_mentor_languages_to_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='session_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Mentor's hourly rate for sessions (in USD or base currency).", max_digits=10),
        ),
    ]
