# Generated by Django 5.2.8 on 2025-12-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_mentorprofile_session_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='embedding',
            field=models.JSONField(blank=True, help_text='384-dimensional vector embedding for semantic matching', null=True),
        ),
    ]
