# Generated by Django 5.2.8 on 2025-12-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_mentorprofile_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, help_text='Last time the mentee was active on the platform', null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, help_text='Last time the mentor was active on the platform', null=True),
        ),
    ]
