# Generated by Django 5.2.8 on 2025-12-15 17:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_mentorprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_positive', models.BooleanField(default=True, help_text='Positive tags (good feedback) vs negative')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MentorCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name or class (e.g., 'code', 'chart-line')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='mentoring.mentorcategory')),
            ],
            options={
                'verbose_name_plural': 'Mentor categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MentorCategoryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary category is shown prominently on profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='mentoring.mentorcategory')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='accounts.mentorprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='MentorFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accounts.mentorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorMenteeRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=20)),
                ('total_sessions', models.IntegerField(default=0)),
                ('completed_sessions', models.IntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, help_text='Total hours of mentoring', max_digits=6)),
                ('mentor_notes', models.TextField(blank=True, help_text='Private notes by mentor about this mentee')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_session_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relations', to='accounts.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_relations', to='accounts.mentorprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags like ["professional", "helpful", "patient", "knowledgeable"]')),
                ('mentor_response', models.TextField(blank=True, help_text="Mentor's response to the review")),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='If False, review is only visible to mentor')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured reviews appear prominently on mentor profile')),
                ('is_approved', models.BooleanField(default=True, help_text='Admins can hide inappropriate reviews')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='accounts.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.mentorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
