# Generated by Django 5.2.8 on 2025-12-15 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentoring', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='scheduling.session'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorcategoryassignment',
            unique_together={('mentor', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='mentorfavorite',
            unique_together={('mentee', 'mentor')},
        ),
        migrations.AlterUniqueTogether(
            name='mentormenteerelation',
            unique_together={('mentor', 'mentee')},
        ),
    ]
