# Generated by Django 5.2.8 on 2025-12-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform fee percentage charged per session (e.g., 10 = 10%)', max_digits=5)),
                ('min_session_price', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum allowed session price for mentors (in EUR)', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='Default platform currency', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
