# Generated by Django 5.2.8 on 2025-12-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Platform Bank Name', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='iban',
            field=models.CharField(blank=True, help_text='Platform IBAN', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='swift_bic',
            field=models.CharField(blank=True, help_text='Platform SWIFT/BIC', max_length=50),
        ),
    ]
