# Generated by Django 5.2.8 on 2025-12-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformsettings_bank_name_platformsettings_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated platform fees', max_digits=12),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='swift_bic',
            field=models.CharField(blank=True, help_text='Platform SWIFT/BIC', max_length=11),
        ),
    ]
