# Generated by Django 4.2.7 on 2025-12-03 10:13

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menteeconversation',
            new_name='mentee_conv_session_a1ac23_idx',
            old_name='mentee_session_idx',
        ),
        migrations.RenameIndex(
            model_name='menteeconversation',
            new_name='mentee_conv_created_7b7d35_idx',
            old_name='mentee_created_idx',
        ),
        migrations.RenameIndex(
            model_name='mentor',
            new_name='mentors_rating_fd2264_idx',
            old_name='mentors_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='mentor',
            new_name='mentors_experie_7ab633_idx',
            old_name='mentors_exp_idx',
        ),
        migrations.AlterField(
            model_name='menteeconversation',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
