# Generated by Django 4.2.7 on 2025-12-03 13:35

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_update_embedding_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeconversation',
            name='message_count',
            field=models.IntegerField(default=0, help_text='Number of messages in this conversation'),
        ),
        migrations.AddField(
            model_name='menteeconversation',
            name='messages',
            field=models.JSONField(default=list, help_text='Message history as list of {role, content, timestamp}'),
        ),
        migrations.AddField(
            model_name='menteeconversation',
            name='profile_analysis',
            field=models.JSONField(default=dict, help_text='Progressive analysis of user profile built over conversation'),
        ),
        migrations.AddField(
            model_name='menteeconversation',
            name='ready_for_recommendations',
            field=models.BooleanField(default=False, help_text='Whether enough info gathered to recommend mentors'),
        ),
        migrations.AddField(
            model_name='menteeconversation',
            name='recommendations_shown',
            field=models.BooleanField(default=False, help_text='Whether recommendations have been shown to user'),
        ),
        migrations.AlterField(
            model_name='menteeconversation',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
