# Generated by Django 4.2.7 on 2025-12-03 15:07

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_menteeconversation_message_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeconversation',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
