# Generated by Django 5.2.8 on 2025-12-29 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_mentorprofile_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Custom chat title', max_length=200, null=True)),
                ('messages', models.JSONField(default=list, help_text='List of message objects [{role, content, timestamp}]')),
                ('conversation_text', models.TextField(blank=True, help_text='Full conversation as text for profile extraction')),
                ('message_count', models.IntegerField(default=0)),
                ('extracted_profile', models.JSONField(blank=True, help_text='Extracted mentee profile from conversation', null=True)),
                ('recommendations_shown', models.BooleanField(default=False)),
                ('embedding', models.JSONField(blank=True, help_text="384-dimensional vector embedding for mentee's needs", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='accounts.menteeprofile')),
            ],
            options={
                'verbose_name': 'Chat Conversation',
                'verbose_name_plural': 'Chat Conversations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
