# Generated by Django 5.2.8 on 2025-12-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='title',
            field=models.CharField(blank=True, help_text='Custom chat title', max_length=200, null=True),
        ),
    ]
