# Generated by Django 5.2.8 on 2025-12-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_chatconversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='embedding',
            field=models.JSONField(blank=True, help_text="384-dimensional vector embedding for mentee's needs", null=True),
        ),
    ]
