# Generated by Django 5.2.8 on 2025-12-29 12:23

import django.core.validators
import django.db.models.deletion
import scheduling.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_duration', models.IntegerField(default=60, help_text='Default duration in minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_recurring', models.BooleanField(default=True, help_text='If True, repeats every week. If False, specific_date is required.')),
                ('specific_date', models.DateField(blank=True, help_text='For non-recurring slots, the specific date', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Can be set to False to temporarily disable a slot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name_plural': 'Mentor availabilities',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('topic', models.CharField(blank=True, default='Mentoring Session', help_text='Topic or subject of the session', max_length=255)),
                ('mentee_notes', models.TextField(blank=True, help_text='Notes from mentee before/during session')),
                ('mentor_notes', models.TextField(blank=True, help_text='Notes from mentor after session')),
                ('objectives', models.JSONField(blank=True, default=list, help_text='List of session objectives')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback from mentee')),
                ('video_room_id', models.CharField(blank=True, help_text='Unique room ID for video call', max_length=100)),
                ('whereby_meeting_id', models.CharField(blank=True, help_text='Whereby meeting ID from API', max_length=100)),
                ('whereby_room_url', models.URLField(blank=True, help_text='Participant URL for Whereby room', max_length=1000)),
                ('whereby_host_room_url', models.URLField(blank=True, help_text='Host URL for Whereby room (for mentor)', max_length=1000)),
                ('video_provider', models.CharField(choices=[('jitsi', 'Jitsi Meet'), ('twilio', 'Twilio Video'), ('daily', 'Daily.co'), ('zoom', 'Zoom')], default='jitsi', max_length=20)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_ended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text="Session price (calculated from mentor's rate × duration)", max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, MAD)', max_length=3)),
                ('payment_id', models.CharField(blank=True, help_text='Reference to payment in billing system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sessions', to='accounts.appuser')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_sessions', to='accounts.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to='accounts.mentorprofile')),
                ('session_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scheduling.sessiontype')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=scheduling.models.session_attachment_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scheduling.session')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attachments', to='accounts.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
