# Generated by Django 5.2.8 on 2025-12-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='topic',
            field=models.CharField(blank=True, default='Mentoring Session', help_text='Topic or subject of the session', max_length=255),
        ),
    ]
