# Generated by Django 5.2.8 on 2025-12-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='whereby_host_room_url',
            field=models.URLField(blank=True, help_text='Whereby host room URL with extra controls'),
        ),
        migrations.AddField(
            model_name='session',
            name='whereby_meeting_id',
            field=models.CharField(blank=True, help_text='Whereby meeting ID for API operations', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='whereby_room_url',
            field=models.URLField(blank=True, help_text='Whereby room URL for participants'),
        ),
        migrations.AlterField(
            model_name='session',
            name='video_provider',
            field=models.CharField(choices=[('whereby', 'Whereby'), ('jitsi', 'Jitsi Meet'), ('twilio', 'Twilio Video'), ('daily', 'Daily.co'), ('zoom', 'Zoom')], default='whereby', max_length=20),
        ),
    ]
