# Generated by Django 5.2.8 on 2025-12-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether a 30-minute reminder has been sent'),
        ),
    ]
