# Generated by Django 5.2.8 on 2025-12-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_session_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, MAD)', max_length=3),
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Session price (calculated from mentor's rate × duration)", max_digits=10),
        ),
    ]
