# Generated by Django 5.2.8 on 2025-12-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_add_price_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='whereby_host_room_url',
            field=models.URLField(blank=True, help_text='Host URL for Whereby room (for mentor)'),
        ),
        migrations.AddField(
            model_name='session',
            name='whereby_meeting_id',
            field=models.CharField(blank=True, help_text='Whereby meeting ID from API', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='whereby_room_url',
            field=models.URLField(blank=True, help_text='Participant URL for Whereby room'),
        ),
    ]
