# Generated by Django 5.2.8 on 2025-12-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_session_whereby_host_room_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='whereby_host_room_url',
            field=models.URLField(blank=True, help_text='Host URL for Whereby room (for mentor)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='session',
            name='whereby_room_url',
            field=models.URLField(blank=True, help_text='Participant URL for Whereby room', max_length=1000),
        ),
    ]
