# Generated by Django 5.2.8 on 2025-12-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_session_whereby_host_room_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback from mentee'),
        ),
        migrations.AddField(
            model_name='session',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5', null=True),
        ),
    ]
