"""
Django settings for LinkDeal project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "corsheaders",
    'accounts.apps.AccountsConfig',  # Use custom config to load signals
    'core',
    'scheduling',
    'mentoring',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "core.middleware.RequestIDMiddleware",
]

ROOT_URLCONF = 'LinkDeal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LinkDeal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        "OPTIONS": {"min_length": 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.Auth0JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
}

if DEBUG:
    # 🔵 DEVELOPMENT: no practical throttling
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []  # no global throttle
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        # our register views use ScopedRateThrottle(scope="register")
        # give it a huge limit so it never hits in dev
        "register": "10000/minute",
        "linking": "10000/minute",  # account linking email requests
    }
else:
    # 🔴 PRODUCTION: enable real throttling
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ]
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": "20/minute",   # unauthenticated requests
        "user": "200/minute",  # per authenticated user
        "register": "5/minute",  # protect registration endpoint from abuse
        "linking": "3/minute",   # limit account linking email requests (prevent spam)
    }

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH0_MGMT_CLIENT_SECRET = os.getenv("AUTH0_MGMT_CLIENT_SECRET")
AUTH0_CUSTOM_NAMESPACE = os.getenv("AUTH0_CUSTOM_NAMESPACE")
AUTH0_MGMT_CLIENT_ID = os.getenv("AUTH0_MGMT_CLIENT_ID")
AUTH0_MENTOR_ROLE_ID = os.getenv("AUTH0_MENTOR_ROLE_ID")
AUTH0_MENTEE_ROLE_ID = os.getenv("AUTH0_MENTEE_ROLE_ID")
AUTH0_SPA_CLIENT_ID = os.getenv("AUTH0_SPA_CLIENT_ID")
AUTH0_ADMIN_ROLE_ID = os.getenv("AUTH0_ADMIN_ROLE_ID")
AUTH0_SUPER_ADMIN_ROLE_ID = os.getenv("AUTH0_SUPER_ADMIN_ROLE_ID")
AUTH0_DB_CONNECTION=os.getenv("AUTH0_DB_CONNECTION")
AUTH0_AUDIENCE = os.getenv("AUTH0_API_AUDIENCE")
AUTH0_DOMAIN = os.getenv("AUTH0_DOMAIN")
AUTH0_ALGORITHMS = ["RS256"]

# Frontend URL for account linking verification emails
FRONTEND_URL = os.getenv("FRONTEND_URL", "")

# Account linking token expiration (in minutes)
ACCOUNT_LINKING_TOKEN_EXPIRY_MINUTES = int(os.getenv("ACCOUNT_LINKING_TOKEN_EXPIRY_MINUTES", "15"))

# =======================
# Whereby Video Configuration
# =======================
WHEREBY_API_KEY = os.getenv("WHEREBY_API_KEY", "")

# =======================
# Email Configuration (SendGrid SMTP)
# =======================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'  # SendGrid requires 'apikey' as username (literal string)
EMAIL_HOST_PASSWORD = os.getenv("SENDGRID_API_KEY")  # Your SendGrid API key
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@linkdeal.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # For error emails

# =======================
# CORS (frontend allowed origins)
# =======================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # React dev
    # "https://app.linkdeal.io",  # example prod domain
]
CORS_ALLOW_CREDENTIALS = True

# =======================
# Security (production hardening)
# =======================
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"