# Generated by Django 5.2.8 on 2025-12-06 16:14

import accounts.models
import accounts.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth0_id', models.CharField(help_text='The user_id returned by Auth0 (e.g. auth0|abcd1234)', max_length=200, unique=True)),
                ('email', models.EmailField(help_text='Email stored locally for quick lookup & linking to profiles.', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text='Duplicate email for UI convenience.', max_length=254)),
                ('field_of_study', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.mentee_profile_picture_upload_path, validators=[accounts.validators.FileSizeValidator(5), accounts.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to='accounts.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Mentor email (duplicate for UI convenience).', max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('professional_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField()),
                ('bio', models.TextField()),
                ('languages', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.mentor_profile_picture_upload_path, validators=[accounts.validators.FileSizeValidator(5), accounts.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('cv', models.FileField(upload_to=accounts.models.mentor_cv_upload_path, validators=[accounts.validators.FileSizeValidator(10), accounts.validators.FileExtensionValidator(['pdf'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='accounts.appuser')),
            ],
        ),
    ]
