# Generated by Django 5.2.8 on 2025-12-06 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='invited_at',
            field=models.DateTimeField(blank=True, help_text='When this user was invited (null if created outside the flow)', null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='The super_admin who invited this user (null if created outside the flow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='accounts.appuser'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active')], default='active', help_text='User status: invited (password not set yet) or active', max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=20),
        ),
    ]
