# Generated by Django 5.2.8 on 2025-12-07 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_invited_at_appuser_invited_by_appuser_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Reason provided when banning the mentor (optional).', null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='banned_at',
            field=models.DateTimeField(blank=True, help_text='When the mentor was banned (if applicable).', null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='banned_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Super Admin who performed the ban.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_mentors', to='accounts.appuser'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('banned', 'Banned')], default='pending', max_length=20),
        ),
    ]
