# Generated by Django 5.2.8 on 2025-12-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mentorprofile_ban_reason_mentorprofile_banned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Reason provided when banning the mentee (optional).', null=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='banned_at',
            field=models.DateTimeField(blank=True, help_text='When the mentee was banned (if applicable).', null=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='banned_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Super Admin who performed the ban.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_mentees', to='accounts.appuser'),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('banned', 'Banned')], default='active', help_text='Mentee account status for access control.', max_length=20),
        ),
    ]
