# Generated by Django 5.2.8 on 2025-12-11 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_menteeprofile_ban_reason_menteeprofile_banned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLinkingVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_auth0_id', models.CharField(help_text='The Auth0 ID of the new social account (e.g., google-oauth2|123)', max_length=200)),
                ('new_email', models.EmailField(help_text='Email of the new social account (should match existing_user.email)', max_length=254)),
                ('token', models.CharField(help_text='Cryptographically secure token for verification', max_length=64, unique=True)),
                ('verified', models.BooleanField(default=False, help_text='Whether this verification has been completed')),
                ('expired', models.BooleanField(default=False, help_text='Whether this verification has expired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this verification token expires (default: 15 minutes)')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the verification was completed', null=True)),
                ('registration_data', models.JSONField(help_text='Stores profile data (full_name, field_of_study, etc.) until verification')),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], help_text='Role chosen during registration', max_length=20)),
                ('existing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linking_verifications', to='accounts.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_ac_token_188a6f_idx'), models.Index(fields=['expires_at'], name='accounts_ac_expires_02d21a_idx')],
            },
        ),
    ]
