# Generated by Django 5.2.8 on 2025-12-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountlinkingverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text="List of selected interests (e.g., ['Web Development', 'AI/ML', 'Data Science'])"),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='session_frequency',
            field=models.CharField(blank=True, choices=[('once_week', 'Once a week'), ('every_two_weeks', 'Every two weeks'), ('once_month', 'Once a month'), ('flexible', 'Flexible')], help_text='Preferred session frequency', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('professional', 'Professional'), ('entrepreneur', 'Entrepreneur'), ('career_changer', 'Career Changer'), ('job_seeker', 'Job Seeker')], help_text='Type of user (Student, Professional, Entrepreneur, Career Changer, Job Seeker)', max_length=50, null=True),
        ),
    ]
